----- --color always -----
[34m[0m[34mtest[0m[34m/[0m[34mcli[0m[34m/[0m[34mcolor[0m
├── [34mdir1[0m
│   ├── [36mbar.txt[0m
│   └── [36mfoo.txt[0m
├── [34mdir2[0m
│   └── [36mqux.txt[0m
├── [36mrun[0m
├── [36mrun.sh[0m
└── [36mrun.sh.exp[0m
----- --color auto -----
test/cli/color
├── dir1
│   ├── bar.txt
│   └── foo.txt
├── dir2
│   └── qux.txt
├── run
├── run.sh
└── run.sh.exp
----- --color never -----
test/cli/color
├── dir1
│   ├── bar.txt
│   └── foo.txt
├── dir2
│   └── qux.txt
├── run
├── run.sh
└── run.sh.exp
